import authServiceApi from '@/services/api/auth-service.api'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta
//           name="description"
//           content="Generated by create next app"
//         />
//         <link
//           rel="icon"
//           href="/favicon.ico"
//         />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{ ' ' }
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs"
//             className={styles.card}
//           >
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a
//             href="https://nextjs.org/learn"
//             className={styles.card}
//           >
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{ ' ' }
//           <span className={styles.logo}>
//             <Image
//               src="/vercel.svg"
//               alt="Vercel Logo"
//               width={72}
//               height={16}
//             />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// export default Home


function Home(): JSX.Element {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')

  async function handleSubmit(): Promise<void> {
    try {
      console.log(username, password, firstName, lastName, 'info')
      await authServiceApi.postSignUpWithPassword({
        username,
        password,
        firstName,
        lastName,
      })
    } catch (error) {
      console.log(error?.response?.data || 'error', 'asdasdasd')
      alert(error?.response?.data || 'error')
    }
  }

  async function handleSubmitLog(): Promise<void> {
    try {
      console.log(username, password, firstName, lastName, 'info')
      await authServiceApi.postLoginWithUsernameAndPassword({
        username,
        password,
      })
    } catch (error) {
      console.log(error?.response?.data || 'error', 'asdasdasd')
      alert(error?.response?.data || 'error')
    }
  }

  async function handleSubmitRef(): Promise<void> {
    try {
      console.log(username, password, firstName, lastName, 'info')
      await authServiceApi.postRefreshToken()
    } catch (error) {
      console.log(error?.response?.data || 'error', 'asdasdasd')
      alert(error?.response?.data || 'error')
    }
  }
  return (
    <div>
      { /* <div className="container">
        <Carousel imageList={carouselImageList} />
      </div> */ }
      { /* <TheaterCard /> */ }
      <div className="container mt-4">
        { /* <Grid lg={2}>
          <Grid.Col
            lg={1}
            sm={2}
          >
            <ContentCard />
          </Grid.Col>
          <Grid.Col
            lg={1}
            sm={2}
          >
            <ContentCard />
          </Grid.Col>
        </Grid> */ }
        <h1>hello</h1>
        <input
          type="text"
          onChange={(e) => setUsername(e.target.value)}
        />
        <input
          type="text"
          onChange={(e) => setPassword(e.target.value)}
        />
        <input
          type="text"
          onChange={(e) => setFirstName(e.target.value)}
        />
        <input
          type="text"
          onChange={(e) => setLastName(e.target.value)}
        />
        <button onClick={handleSubmit}>save</button>
        <button onClick={handleSubmitLog}>sign</button>
        <button onClick={handleSubmitRef}>ref</button>
      </div>
      { /* <ScrapbookTrend />
      <ProductCarousel />
      <CouponCarousel />
      <FeaturedCategory />
      <CampaignCarousel />
      <ProductCarousel />
      <ProductCarousel />
      <CouponCarousel />
      <EditorialContent /> */ }
    </div>
  )
}

export default Home